### ISSUE TITLE
demo instructions don't work

### ISSUE THREAD

**Issue by sils** [tushar-rishav/Blogular#3]
https://github.com/tushar-rishav/Blogular#for-demo

```
lasse@lssteady ~/prog % g cl git@github.com:tushar-rishav/Blogular.git
Cloning into 'Blogular'...
remote: Counting objects: 121, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 121 (delta 0), reused 0 (delta 0), pack-reused 118
Receiving objects: 100% (121/121), 714.15 KiB | 836.00 KiB/s, done.
Resolving deltas: 100% (35/35), done.
Checking connectivity... done.
lasse@lssteady ~/prog % cd Blogular 
lasse@lssteady ~/prog/Blogular (git)-[master] % python -m SimpleHTTPServer 1234         
/usr/bin/python: No module named SimpleHTTPServer
```

**Comment by tushar-rishav** [comment]
@sils1297  Probably you are using Python 3. Actually the `SimpleHTTPServer` module has been merged into `http.server` in Python 3. Try running `python3 -m http.server <port_number>`  and let me know if it works.  Meantime I will update the Readme :)

**Comment by sils** [comment]
why would I use python 2 ^^ :P

2016-02-15 21:25 GMT+01:00 Tushar notifications@github.com:

**Comment by tushar-rishav** [comment]
@sils1297 Maybe because [Coala](https://github.com/coala-analyzer/coala) supports Python 3+ :P
Did that work?

**Comment by tushar-rishav** [comment]
@sils1297 Yeah right. So I can assume it worked then? :smile:

**Comment by sils** [comment]
indeed
